### ISSUE TITLE
Add delete fxnality for Watchlist and Note type categories

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#134]
Need to implement a delete mechanism for the two categories so that unused categories are deleted and those that can't be deleted are flagged/archived and hidden from future selection as types.

**Front end**
1. Any type that gets deleted should not be selectable when creating new watchlists or notes
2. Deleted types should disappear from the respective grids under Admin. (If there is a need later to view or undelete archived types, we can handle that then. Probably don't need it now).
3. Need a confirmation notification especially since we are not allowing the user to undo this action.

**DB**
New boolean field in hit_category and note_type tables to flag archived recs

**Back end**
Delete endpoints and handlers

**Comment by tjwdev** [comment]
As further clarity: Edit functionality was also added to note category since functionally hit category and note category are equivalent and it would not stand to reason to have one editable and the other not.
