### ISSUE TITLE
manage users | odd behavior

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#155]
- snackbar for failures on admin forcing password change
- snackbar for non-matching passwords for password assignment
- Deleting user not forcing archive in the database
- cannot add user with no roles i.e. "View flights" min role

**Comment by gtasautumn** [comment]
Add role validation on the front end so the user cannot submit a new user without a role selected.

Default role shd be View Flights (TBD)

**Comment by kasimhelil** [comment]
This is resolved on a previous commit
