### ISSUE TITLE
QBRB | conditional values are incorrect

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#157]
User inputs Age >=18 and <=30. Drools rule gets saved as ;

<img width="862" alt="Screen Shot 2020-08-13 at 11 11 43 AM" src="https://user-images.githubusercontent.com/20464494/90152406-c842c880-dd55-11ea-9aaa-e8ec95a2782c.png">

Passenger Age is greater than or equal to 30
Passenger Gender is 'F' | rule "NCV1:ADMIN:0"
date-effective "13-Aug-2020"
when
$p:Passenger()
$f:Flight()
$flpaxlk:FlightPassengerLink(passengerId == $p.id, flightId == $f.id)
$pcb:PassengerDetails(passengerId == $p.id, age <= 18, age >= 30, gender == "F")
then
resultList.add(new RuleHitDetail(%dL, %dL, "NCV1", $p, null, "Passenger Age is less than or equal to 18///Passenger Age is greater than or equal to 30///Passenger Gender is 'F'"));

**Comment by gtasautumn** [comment]
THis is OBE by the updated qb component
