### ISSUE TITLE
Roles - add View Flights

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#221]
Add role validation on flights fetches
Add role back to roles table

**Comment by tjwdev** [comment]
A small concern with this ticket is that all users who do not currently have view flights will need to be grandfathered in; Though this ticket does not say it, the intended goal is to keep "View Flights" in essence the default role.

**Comment by gtasautumn** [comment]
Anybody who has another role is kosher. Anybody who doesn't:

```
select *
from user u
where u.user_id not in 
(select user_id from user_role)
```

**Comment by tjwdev** [comment]
Agreed, it was only a small concern. I was just tracking it as part of it since I didn't want to forget we'd need an update like it.

**Comment by gtasautumn** [comment]
Is the script for this complete?

**Comment by gtasautumn** [comment]
Correction to my earlier comment, the View Flights role must be assigned to all system users, not just those without another role.
