### ISSUE TITLE
Seat Chart Diagram | ability to search for passenger name

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#229]
Users should be able to search for a different passenger's name and see results highlighted on the view in addition to the current passenger.

**Comment by sylbakar** [comment]
Tested in dev. The search functionality worked for last name and first name however for first name, it did not work.

**Comment by sylbakar** [comment]
Tested in dev. The search functionality worked for last name, first name and middle name as expected. The test passed.
