### ISSUE TITLE
Date/Time Picker | Reset causes error

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#239]
the reset probably needs a redo after selecting the new date/time picker, which is great.

**Comment by dje04001** [comment]
×
RangeError: Invalid time value
(anonymous function)
http://localhost:3000/static/js/authed.chunk.js:13744:34
  13741 | fieldNames.forEach(name => {
  13742 |   if (name === "etaStart" || name === "etaEnd") {
  13743 |     const date = new Date(fields[name]);
> 13744 |     paramObject[name] = date.toISOString();
        |                              ^  13745 |   }
  13746 | 
  13747 |   if (Object(_utils_utils__WEBPACK_IMPORTED_MODULE_6__["hasData"])(fields[name])) {
View source
parameterAdapter [as paramAdapter]
src/pages/vetting/Vetting.js:203
  200 | }
  201 | 
  202 | const fieldNames = Object.keys(fieldscopy);
> 203 | fieldNames.forEach(name => {
      | ^  204 |   if (name === "etaStart" || name === "etaEnd") {
  205 |     const date = new Date(fields[name]);
  206 |     paramObject[name] = date.toISOString();
View compiled
FilterForm.fetchWithParams
src/components/filterForm/FilterForm.js:136
  133 |   }
  134 |   params += "action=get";
  135 | } else {
> 136 |   params = this.props.paramAdapter(this.state.fields);
      | ^  137 | }
  138 | 
  139 | this.fetchData(id, params);
View compiled
FilterForm.onFormSubmit
src/components/filterForm/FilterForm.js:166
  163 | onFormSubmit(e) {
  164 |   e.preventDefault();
  165 | 
> 166 |   this.fetchWithParams();
      | ^  167 | }
  168 | 
  169 | // bind children containing form data (datafield prop) to the ev handler and state
View compiled
▶ 22 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by kasimhelil** [comment]
I think this is fixed on previous commit
