### ISSUE TITLE
Passenger Details | API tab, co-travelers aka Passenger on Reservation not working

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#242]
The grid is not displaying passengers that share the same PNR record locator number as expected. Check our a PNR tab displaying more than one traveler on the reservation, then check out the APIS tab and see an empty table.

**Comment by sylbakar** [comment]
I tested on Dev environment and found Passenger on Reservation table is populated with all pnr passengers sharing the same PNR record locator number. The test passed.
