### ISSUE TITLE
Menu bar cleanup | remove dashboard, reorder items, update logo

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#253]
- [x]  Flights, Vetting, Tools, Admin

- [x] Remove "Dashboard menu item", rewire logo link to go to nowhere for now

- [ ] Update Logo to reflect latest graphic

**Comment by gtasautumn** [comment]
Dashboard link is removed and the logo points at Flights as part of the translation branch. Do you want the link removed?
