### ISSUE TITLE
Watchlist | cannot add passenger

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#267]
TypeError: _vals$dob.replaceAll is not a function
preSubmit [as paramCallback]
src/pages/tools/watchlist/WLModal.js:141
  138 | const documentNumber = vals["documentNumber"];
  139 | const firstName = vals["firstName"];
  140 | const lastName = vals["lastName"];
> 141 | const dob = vals["dob"]?.replaceAll("/", "-");
      | ^  142 | const categoryId = vals["categoryId"];
  143 | const action = mode === "Add" ? "Create" : "Update";
  144 | const recordId = mode === "Add" ? "null" : id;
View compiled
Form.onFormSubmit
src/components/form/Form.js:124
  121 |   ? [this.props.recordId, this.state.fields]
  122 |   : [this.state.fields];
  123 | 
> 124 | const parsedParams = hasData(this.props.paramCallback)
      | ^  125 |   ? this.props.paramCallback(params)
  126 |   : params;
  127 |

**Comment by gtasautumn** [comment]
This is OBE by backend PR #1891
