### ISSUE TITLE
Admin | manage users bug

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#273]
login as admin
find existing user that is not an admin, that has the manage cases role
remove the manage cases role
logout of admin
try to login as the user modified
notice how you can't login as that user

**Comment by kasimhelil** [comment]
With the latest code from dev branch, I followed these steps, but I was able to login.

**Comment by gtasautumn** [comment]
We are replacing the manage cases role with Manage Hits (Hit Manager?). All users now have the view flight role at least, so this one is OBE.
