### ISSUE TITLE
Passenger Details | Links to other flights / passengers

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#279]
The legacy web application has links to other flight/passengers in the last names, and flight IDs

APIS | Passengers on PNR table, Last Names are links to passenger details page
PNR | PNR Names table, Last Names are links to passenger details page

History | Flight numbers links to passenger details page

**Comment by kasimhelil** [comment]
Should the Flight Numbers link be to the flightPax instead of passenger details?
