### ISSUE TITLE
Bug - cypherAuth endpoint returns text/plain

### ISSUE THREAD

**Issue by tjwdev** [US-CBP/GTAS-UI#309]
The endpoint for getting neo4j authorization credentials returns a String to the front-end. The genericService attempts to json-ify it, resulting in the response being set to a Syntax Error. 

While it's possible to fix this on the  front-end, I think the proper solution is to add a second end point that returns a json object, deprecate original to slate for eventual removal.

**Comment by gtasautumn** [comment]
This is resolved by PR #310
