### ISSUE TITLE
Watchlist | delete is watchlist row is not working 

### ISSUE THREAD

**Issue by kasimhelil** [US-CBP/GTAS-UI#322]

**Comment by gtasautumn** [comment]
Is this the same as issue #134? Problem there (I thought) was that wl cats could only be deleted if they weren't already in use, so you could delete new ones but not some of the existing ones.

**Comment by kasimhelil** [comment]
No, deleting any wl item was broken but fixed on one of the previous push! For wl items that are in use, we still get 500, I think.
