### ISSUE TITLE
elastic search results do not display correct ETD/ETA for flights

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#349]
It appears to be showing the flight date and not the correct timestamp. Every flight starts and ends at 4:00am which tracks to our UTC offset.

**Comment by sylbakar** [comment]
ETD/ETA columns displayed too old data like from year 2020 instead of most recent data:
![image](https://user-images.githubusercontent.com/49790901/113759586-396b2d80-96e3-11eb-898e-e15fd7c40943.png)
