### ISSUE TITLE
PVL Filters | Hit Categories is hidden until you toggle the date picker to on

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#352]
<img width="260" alt="Screen Shot 2020-10-28 at 6 25 27 PM" src="https://user-images.githubusercontent.com/20464494/97503215-03af6500-194b-11eb-8bcf-452e1b3f029f.png">
<img width="251" alt="Screen Shot 2020-10-28 at 6 25 20 PM" src="https://user-images.githubusercontent.com/20464494/97503224-04e09200-194b-11eb-8b20-ce9204f46ed7.png">

**Comment by tjwdev** [comment]
This appears to be resolved by merging Feat/gray background into dev
