### ISSUE TITLE
Styling | manual hit modal

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#417]
<img width="1297" alt="Screen Shot 2020-11-05 at 1 02 22 PM" src="https://user-images.githubusercontent.com/20464494/98278892-379c1300-1f67-11eb-8380-ba5d3a5477f7.png">

a little too wide. I think some of the other modals are a bit tighter style-wise

**Comment by gtasautumn** [comment]
think I just fixed that.
