### ISSUE TITLE
Bug | Hit categories on the PVL

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#418]
I'm seeing something strange on the PVL where the filter isn't displaying the categories, and I'm unable to select + filter on them

<img width="240" alt="Screen Shot 2020-11-05 at 1 09 13 PM" src="https://user-images.githubusercontent.com/20464494/98279605-24d60e00-1f68-11eb-879a-488da286b953.png">

**Comment by tjwdev** [comment]
Missed mapping. Fix pushed and awaiting PR.

**Comment by gtasautumn** [comment]
this is merged, moving to done.
