### ISSUE TITLE
PNR | Credit Card Expiration date formatting

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#445]
We should fix this element once and for all... the data comes in almost always in the mm/yy format

<img width="169" alt="Screen Shot 2020-11-09 at 1 57 14 AM" src="https://user-images.githubusercontent.com/20464494/98509268-e58d1300-222e-11eb-82b8-f04f08fbb248.png">

**Comment by gtasautumn** [comment]
FYI, this fix doesn't affect how we import that data point or how it displays in the qbrb (that's covered by ticket #244 ).
