### ISSUE TITLE
PaxDetails | Hit conditions cleanup

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#465]
"Bag bagMeasurements.bagCount is greater than or equal to 5$$$" probably isn't going to make sense to an end user. If it's at all possible, we should think of a way to clean this up.

**Comment by dje04001** [comment]
<img width="791" alt="Screen Shot 2020-11-11 at 9 05 54 AM" src="https://user-images.githubusercontent.com/20464494/98821130-1de24c00-23fd-11eb-9071-f6cf201b0c54.png">

**Comment by gtasautumn** [comment]
Just added a fix for this last night to the feat/fab branch. 
![ruleConditions](https://user-images.githubusercontent.com/49160279/99104485-0c40a600-25af-11eb-987a-1ed97918eaa9.png)
