### ISSUE TITLE
PaxDetail - Hits not refreshing in Summary

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#484]
No refresh after we add a manual hit. Do we need to poll for changes here or is hit data updated realtime? Need to also ensure that the action button options update correctly. We are disabling "Create Manual Hit" for users who already have a hit.

Possibly need to review the use cases for adding a manual hit when the user has a hit from a different source.

**Comment by dje04001** [comment]
I'm not sure what the use case would be where a user would need to add a manual hit to a passenger that already has hits. I suppose if the user groups concept evolves, we may need the ability to for a user to add a manual hit because they are unaware of a hit existing outside of their user group.
