### ISSUE TITLE
Passenger Details | PNR tab, add Leg number column to Itinerary table

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#505]
<img width="127" alt="Screen Shot 2020-11-23 at 11 20 03 AM" src="https://user-images.githubusercontent.com/20464494/99986962-d7d2a400-2d7d-11eb-90ae-11e653bdab04.png">

**Comment by gtasautumn** [comment]
Are you running latest? My local dev has the flight leg field included.

![flightleg](https://user-images.githubusercontent.com/49160279/100009283-acab7d00-2d9c-11eb-9ebe-ff0e5d5385c3.JPG)
