### ISSUE TITLE
Datetime picker seconds filtering error

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#516]
Datetimes in Audit Log, eg, are recorded down to the second, but the datetime picker stops at minutes. This can cause discrepancies for users filtering records by minutes since records that are displayed with a timestamp of say 2:15 PM on a given day will not show up if you search with the end date set to 2:15 PM unless their truncated seconds timepart is exactly 00 seconds.

We need to ensure that all pages with date filters are correctly accounting for truncated timeparts by rounding the end date up to the next whole visible timepart.

Example:

     start date >= 1:00 PM, end date < 2:15 PM

should be adjusted to:

     start date >= 1:00 PM, end date < 2:16 PM
so all the 2:15 PM records are included

The start date seconds should already default to 00, but verify.

**Comment by sylbakar** [comment]
Tested in dev and found expected result.
