### ISSUE TITLE
PaxDetail - PNR itinerary flight legs are backward

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#523]
the legs are listed in reverse chronological order

**Comment by gtasautumn** [comment]
![pnritinerary](https://user-images.githubusercontent.com/49160279/100635077-0f050000-32fe-11eb-8b6c-14dbbdd547c0.JPG)

**Comment by sylbakar** [comment]
Tested in dev environment and found legs listed chronological order. The test passed.
