### ISSUE TITLE
FlightPax | group by PNR when there there are no pax w/ hits on the flight

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#527]
<img width="1060" alt="Screen Shot 2020-12-01 at 10 31 23 AM" src="https://user-images.githubusercontent.com/20464494/100761067-74b9c080-33c0-11eb-9556-c83aeba76c1d.png">

**Comment by dje04001** [comment]
This is on that other, non-dev branch

**Comment by tjwdev** [comment]
This is related to us swapping column headers now based on which tab we select rather than it being static across both.

**Comment by tjwdev** [comment]
This should be fixed as of hit_category branch merge.
