### ISSUE TITLE
Aggregate hit flags not sorting correctly

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#536]
**Describe the bug**
The aggregate hits flags are currently sorting so that the low severity hits are weighted more heavily than medium or high. This is the reverse of what we need. The sort currently orders the hits based on the number of low severity hits first, so the high severity hits can't be ordered.

**To Reproduce**
1. Go to Flights
2. Click once to sort the Hit Aggregates column ascending
3. Observe that the sort orders the hits from the fewest to the most **low severity** hits
4. Click the Hit Aggregates column again to sort descending
5. Now the flights are ordered from most to fewest **low severity** hits.

**Expected behavior**
The greatest weight should be applied to the **high severity** hits so that sorting by descending hits should arrange the flights with the most high severity hits at the top.

**Screenshots**
![hitaggdesc](https://user-images.githubusercontent.com/49160279/101195749-df236880-362d-11eb-994a-92c693a1bfc9.JPG)

**Comment by sylbakar** [comment]
I tested on Dev Environment and found correct sorting order as expected. The test passed.
