### ISSUE TITLE
paxDetail - flight leg stepper not refreshing

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#540]
**Describe the bug**
When you view a passenger with historical hits and click the details link (Summary tab > Historical Hits card > Details field), the data in the sidebar updates to reflect the pax info for the historical hit, but the stepper does not get refreshed. When navigating from a future event to one in the past, the stepper makes it appear as if the flight hasn't arrived at the user's port yet. When navigating between flights with different legs and ports, the ports don't get updated.

**To Reproduce**
1. Go to paxDetail on a passenger who has historical hits
2. Click on Details under Summary tab > Historical Hits
3. verify that the sidebar spinner displays and the flight, seat, etc. data updates
4. Observe that the flight leg stepper at the bottom of the sidebar does not update.

**Expected behavior**
All relevant data in the sidebar should be updated when a new flight pax is loaded. If the record is a PNR record, verify that the stepper legs match those shown under PNR in the Itinerary card

**Comment by sylbakar** [comment]
I tested on Dev environment and found that all relevant data were  updated in the sidebar  when a new flight pax was loaded as expected. The test passed.
