### ISSUE TITLE
Redirect to blank login page

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#546]
**Describe the bug**
When the user's timeout has expired or they haven't logged in and try to go directly to a page in the authorized bundled (anything after the login), the site redirects to login but the page initially loads blank and you have to refresh.

**To Reproduce**
1. With the browser (chrome)  on the login page, open devtools and delete the browser cache: Application tab > Storage > Clear site data.
2. Navigate directly to an authorized page, eg localhost:3000/gtas/admin, by pasting the url into the browser.
3. The site will immediately redirect to the login page, but it will be blank until you hit refresh

**Expected behavior**
The site should render the login page without needing a refresh.

**Comment by sylbakar** [comment]
Tested in dev environment and found expected result. The test Passed.
