### ISSUE TITLE
PaxDetail Prior Event Notes column data missing

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#547]
**Describe the bug**
The Note Type column is missing data in the Prior Event Notes card on the Summary page.

**To Reproduce**
1. Go to paxdetails for a user with previous hits
2. Click on Add Event Note under the green fab button
3. Add a note and save it
4. Verify that the note displays in the Event Notes card
5. Click on the Details link on one of the Historical Hits records
6. Verify that the note you entered now shows up in the Prior Event Notes card with the category missing.

**Expected behavior**
The category should show up in the Prior Event Notes card table.

**Screenshots**
![notetypemissing](https://user-images.githubusercontent.com/49160279/101268518-bb494b00-3731-11eb-994d-8856edf93f17.JPG)

**Comment by sylbakar** [comment]
I tested on dev environment and found  Note Type column is populated with data in the Prior Event Notes card as expected. The test passed.
