### ISSUE TITLE
Attachment Modal translations, layout, warnings

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#550]
**Describe the bug**
The attachment modal has untranslated text in the drag-and-drop area, and the layout needs cleaning up. Long filenames do not wrap, but go over the edge of the modal. In addition, there's no indication to the user that there is a file limit of 4. The modal just rejects the files and clears itself.

**To Reproduce**
1. Go to PaxDetail and click the action button to add an attachment
2. Add more than 4 attachments
3. Observe that no files are listed and that no error/warning is displayed
1. Add an attachment with a very long name
2. Observe that text runs over the modal edge.

**Expected behavior**
It should display on the modal or in a separate notification the reason a file or set of files can't be uploaded. The modal content should wrap and fit within the modal boundaries, and (if possible) the content in the drag area should be marked with translation tags.

**Screenshots**
![attachments1](https://user-images.githubusercontent.com/49160279/101272078-f9a53100-3756-11eb-8434-62c5e047f187.JPG)

untranslated text:
![attachments2](https://user-images.githubusercontent.com/49160279/101272079-f9a53100-3756-11eb-8301-fc2207979b32.JPG)

**Comment by sylbakar** [comment]
Tested in dev. Any file larger than 1 MB is not uploaded and there's no indication for not uploading.

**Comment by sylbakar** [comment]
Tested in dev and found expected result. I will create a new  ticket for the bigger file uploading issue.
