### ISSUE TITLE
Admin | Code Editor | Page title "Code Editor" is not present

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#554]
**Describe the bug**
Admin | Code Editor | Page title "Code Editor" is not present
**To Reproduce**

**Expected behavior**
Expect to see Page title "Code Editor" is there

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gtasautumn** [comment]
This issue was addressed in a previous merge. Moving it to done. Please test and close.

**Comment by sylbakar** [comment]
I tested on Dev and local  Environments and found expected result.
