### ISSUE TITLE
Admin | Settings | Edit button option is not available

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#555]
**Describe the bug**
Admin | Setting, there is no Edit button only Submit button is there.
**To Reproduce**
4. Expect to see Edit button to update the information.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gtasautumn** [comment]
This was implemented as a new feature in PR #458
