### ISSUE TITLE
QBRB - Flight leg data not displaying

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#560]
**Describe the bug**
The Flight Leg entity has `destination` and `origin` properties whose values are derived from airport codes. These values save correctly, but are not displayed when you open an existing rule that uses this entity.

**To Reproduce**
1. Go to Tools > Rules
2. Click on the green floating action button to create a new rule
3. Create a rule for **Flight Leg** > **destination** > **equals** > [pick any value]
4. Save the rule
5. Open the rule and observe that the value you chose for the destination is now blank

**Expected behavior**
The rule value should display correctly.

**Screenshots**
![qbrbflightleg](https://user-images.githubusercontent.com/49160279/101678195-9c95cd80-3a2b-11eb-8353-964081c35816.JPG)

**Comment by sylbakar** [comment]
Tested in dev environment and  found expected behavior. The Test Passed.
