### ISSUE TITLE
Routing - unhandled endpoint requests do not redirect correctly 

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#562]
**Describe the bug**
When you enter an invalid uri, eg "/gtas/admin/sdfsdfs", the system loads a blank page.

**To Reproduce**
1. Login as admin
2. Enter an invalid admin endpoint into the browser and hit enter
3. Observe that the site serves a blank content page under the header
(See PR #640  for examples of endpoints to test)

**Expected behavior**
Invalid endpoints should trigger the 404 handler as it does elsewhere. Need to verify that all invalid endpoints are correctly handled.

**Screenshots**
Example of the 404 handler showing up correctly:
![404](https://user-images.githubusercontent.com/49160279/101799484-33b95e80-3ada-11eb-872c-ad39fb823d75.JPG)

**Comment by sylbakar** [comment]
When you go to admin page and hit refresh see the following:
![image](https://user-images.githubusercontent.com/49790901/114250792-e1dff280-996c-11eb-86cc-aaa7186a64ea.png)

**Comment by gtasautumn** [comment]
This issue is covered in another ticket, this is not related to routing.
