### ISSUE TITLE
Seats - page is accessible to unauthorized users

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#563]
**Describe the bug**
Users without the Admin or View Passengers role are able to navigate to the seats page

**To Reproduce**
1. Login as an admin
2. On the Flights page, click any flight
3. Click any passenger
4. On the PaxDetails page, click the seat number link in the sidebar
5. Verify that the page loads and save the link to your bookmarks.
6. Log out and log back in as any user without Admin or View Passengers roles
7. Click the bookmarked link for the Seats page
8. Observe that the site does not redirect or warn the user, but generates an error.

**Expected behavior**
The site should load the unauthorized page with a message that the user can't access it. The page should not generate an error.

**Comment by sylbakar** [comment]
Tested in dev environment and found expected result as page is not accessible to unauthorized users. The test passed.

**Comment by sylbakar** [comment]
The test passed.
