### ISSUE TITLE
Signup Users Role modal - messy layout

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#564]
**Describe the bug**
Once a signup request is approved by an admin, the admin is prompted to assign roles to the user. This modal escaped the last restyling overhaul, looks pretty bad.

**To Reproduce**
1. With a pending signup request, log in as Admin
2. Click on Admin > Signup Requests
3. Find a pending request in the grid and click `Approve`
4. Observe the that role selection modal is too small for its content

![signuproles](https://user-images.githubusercontent.com/49160279/101805472-cb21b000-3ae0-11eb-8ebb-d1286609864d.JPG)

**Expected behavior**
This modal needs the same layout structure as the other modals.

**Question**
Would it make sense here to launch the standard Edit User modal? This gives the admin the chance to review/update fields we don't display in the grid like phone number, email, etc.

**Comment by sylbakar** [comment]
Tested in Dev Environment and found expected  role selection modal size. The test passed.
