### ISSUE TITLE
Rules - rules data gets stuck on "All Rules"

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#567]
**Describe the bug**
When you navigate to Rules, the data on the `My Rules` tab is correct the first time. But if you click `All Rules` and back to `My Rules`, the data always shows the `All Rules` data.

**To Reproduce**
1. Create rules using at least 2 different user accounts
2. Go to Tools > Rules
2. Click back and forth on the tabs
3. Observe that the data is only correct the first time you view `My Rules`

**Expected behavior**
The data should filter correctly every time.

**Comment by sylbakar** [comment]
Tested in Dev environment and found expected behavior.  The Test Passed.
