### ISSUE TITLE
QBRB - date fields to datepicker control

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#568]
**Describe the bug**
The date fields on the qbrb modal need to use the datepicker input control

**To Reproduce**
1. Go to Rules
2. Click on the green action button to add a new rule
3. Observe that the modal has 2 fields for start date and end date but both are text inputs.

**Comment by sylbakar** [comment]
Tested in dev environment and found control in date fields. The test passed.
