### ISSUE TITLE
Change Password Validation moving input focus

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#571]
**Describe the bug**
If you try to change your password, sometimes it (the validation piece?) kicks you out of the current input box unexpectedly. It mostly happens after getting an error the first time.

**To Reproduce**
1. Go to Change Password under the site header
2. Enter an invalid `Old Password` to ensure you get an error
3. Enter a valid password like **pegPEG123!** in `New Password` and in the confirmation
4. Error returns as expected
5. Click into `New Password` again and try to enter the same password
6. _Sometimes_ it kicks you out after the first character
7. If it allows you to keep typing, enter a longer version of the like **pegPEG123!@#**
8. Observe that it kicks you out as soon as the content matches what's in the confirmation input.

**Expected behavior**
The system should not move focus from one control to another here. It should indicate invalid fields and possibly disable the submit button.

**Comment by sylbakar** [comment]
Tested in dev environment and found expected behavior. The test passed.
