### ISSUE TITLE
About page - contents shifted downward

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#573]
**Describe the bug**
There is an empty div at the top of the page that's shifting content below the bottom padding of the main container. In the image below, the light blue highlights an empty div that's throwing the layout off.

![aboutjank](https://user-images.githubusercontent.com/49160279/101959017-84ac7e00-3bd2-11eb-95c2-e25ac8dfb867.JPG)

**Comment by sylbakar** [comment]
I tested on Dev Environment and found  no empty div as expected . The test passed.
