### ISSUE TITLE
Passenger Detail | Summary | Current Hits Summary | Conditions text looks like link

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#583]
**Describe the bug**
Conditions column text color is light blue and underlined looks like link and if you hover on it full text is not displayed

**Expected behavior**
We  expect to see full text  if you hover on text.

**Comment by gtasautumn** [comment]
SHould be resolved in DEV

**Comment by sylbakar** [comment]
I tested on DEV environment and found the expected result.
