### ISSUE TITLE
Vetting - 400 error no data

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#585]
**Describe the bug**
Vetting page is not returning data, server is returning a 400 error. See the DEV env.

**Screenshots**
![vetting400](https://user-images.githubusercontent.com/49160279/102444977-67274c00-3ff8-11eb-8dfe-68d0827f88f0.JPG)

**Environment/Browser**
DEV/Chrome

**Comment by tjwdev** [comment]
The table ug_user_join was missing connections for a handful of users. All new users created are intended to be folded under a default user_group. There is a check when retrieving vettable items that references the user_group, and it fails when there is no user group for a user. It is unknown at this time why the join wasn't present for these users. 

The bug has been fixed for now by reapplying those joins manually in the table. This ticket will remain open for now in case of re occurrence, and we can revisit at another time when we're satisfied with an explanation.,

**Comment by tjwdev** [comment]
This is fixed by https://github.com/US-CBP/GTAS/pull/1999
