### ISSUE TITLE
Reset Password functionality missing confirmation dialog

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#589]
**Describe the bug**
After entering user ID and submitting form to reset password, nothing happens. Users will expect some kind of confirmation, and possibly redirection to the login page.

**To Reproduce**
1. Go to login page
2. Click on reset password link
3. Input valid user ID in form and click submit
4. Notice a confirmation is not displayed

**Expected behavior**
Covered in the description

**Desktop (please complete the following information):**
in Dev

**Comment by sylbakar** [comment]
I tested in dev and found a confirmation was displayed as expected behavior. The test passed.
