### ISSUE TITLE
Login/Logout error

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#597]
**Describe the bug**
A second login and logout results in a blank page instead of being redirected to the login screen. 

**To Reproduce**
1. Login as any user
2. Logout
3. Login again as the same user in the same browser window
4. Logout
5. Notice a blank web page

**Expected behavior**
User should be redirected to the login screen.

**Comment by sylbakar** [comment]
Tested in dev environment and found expected result. The test Passed.
