### ISSUE TITLE
Audit log / Error log Filter Form Reset Error

### ISSUE THREAD

**Issue by kasimhelil** [US-CBP/GTAS-UI#605]
**Describe the bug**
Resetting the filter form on Audit log and Error Log pages throws an error due to missing action types

**To Reproduce**
1. Go to 'Admin/Audit Log' and 'Admin/Error log'
2. Click on 'Reset' on the side nav
3. See error on the console, and notice you won't get any table data

**Expected behavior**
Resetting the filter form should not throw an error, it should filter the data based on the default input values.

**Comment by sylbakar** [comment]
Tested in DEV environment and found expected behavior. The test Passed.
