### ISSUE TITLE
FlightPax | group by PNR record locator is not working

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#621]
**Describe the bug**
Group by PNR record locator is not working on the FlightPax grid, both in "All passengers" tab and the "hits only" tab

**To Reproduce**
1. Go to FlightPax for anyflight
2. Click on the group by PNR button
3. See blank page

**Expected behavior**
This should group passengers by their PNR record locator numbers.

**Comment by sylbakar** [comment]
Tested in dev environment and found expected behavior.  The test passed.
