### ISSUE TITLE
Vetting - filter changes when you switch to datepicker

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#623]
**Describe the bug**
On the Vetting/PVL, the data appears to sort differently immediately after you click **Show Date Time Picker**, but the difference is that the ranges are different. The range picker defaults to 96 hours before and after the current date, but the datetime picker goes from today (minus 6 hours?) to 7 days from now.

**To Reproduce**
1. Go to Vetting/PVL
2. Observe the order of the data in the Timer column
3. Click **Show Date Time Picker**
4. Observe that the data reloads and has different start and end dates

**Expected behavior**
The data should probably not reload just by switching the date picker type, but it's acceptable for now. But the default ranges on both picker types should match.

1. We should add a 0-hour option to the range picker dropdowns.
2. Set the default selected range to -6 hours and +96
3. Set the default selected datetime picker values to -6 hours and +96 hours to match

**Screenshots**

Initial data
![vettingdatesortBEFORE](https://user-images.githubusercontent.com/49160279/105868729-7967b300-5fc4-11eb-9f8a-67155878d23d.JPG)

After clicking **Show Date Time Picker**
![vettingdatesortAFTER](https://user-images.githubusercontent.com/49160279/105869050-d499a580-5fc4-11eb-9fa8-ce36a09f489a.JPG)

**Environments:**
 - Dev
 - local

**Comment by sylbakar** [comment]
Tested in dev environment and found default matched start and end date when switched to date picker.
