### ISSUE TITLE
PVL | Reset filter error 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#625]
**Describe the bug**
Reset filter is resulting in an error after using date/time picker

**To Reproduce**
1. Go to PVL
2. Click on the filter by note type and check one note type to filter on
3. Use date/time picker to set the date range for the filter, and submit filter request
4. Click reset button, and see blank page

**Comment by sylbakar** [comment]
Tested in dev environment and found the page populated.
