### ISSUE TITLE
Watchilst | add passenger failing to add record

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#635]
**Describe the bug**
The modal form for adding passenger appears to work on submit, but no watchlist record is added on either the UI or back end.

**To Reproduce**
1. Go to Toos>Watchlist
2. Click on add passenger 
3. Add FN, LN, DOB, and click submit
4. See that the record has not been added to the table

**Expected behavior**
Assuming no manual entry errors in the date/name fields, clicking submit should add the passenger to the watchlist

**Comment by sylbakar** [comment]
Tested in dev environment and found expected behavior. The test passed.
