### ISSUE TITLE
Seat map - missing middle names

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#637]
**Describe the bug**
The passenger middle names are missing from the popover (when you click the seat buttons) until after you've done a search on the page.

**To Reproduce**
1. On the seats map page, click any reserved seat (any seat button that's not gray)
2. Observe that the popover shows the passenger first and last name, but no middle name
3. Search for any first, last or middle name on the sidebar filter
4. Observe that the same passengers now have the middle names showing up.

**Expected behavior**
Middles names should always show up

**Screenshots**
![missingmi1](https://user-images.githubusercontent.com/49160279/106951142-614b0e80-66fd-11eb-81bf-7f517ee92bd8.JPG)
![missingmi2](https://user-images.githubusercontent.com/49160279/106951143-61e3a500-66fd-11eb-892a-ec405604dbaf.JPG)

**Envirnoments**
found this locally and in dev

**Comment by sylbakar** [comment]
Tested in dev environment and found Passenger middle names were displaying from the popover (when you click the seat buttons) as expected however filtering with middle name was not showing any results.

**Comment by sylbakar** [comment]
Tested in dev environment and found Passenger middle names were displayed from the popover (when you click the seat buttons) and Search worked for first name, middle name and last name. The test passed.
