### ISSUE TITLE
Spinner animation bug

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#666]
**Describe the bug**
The spinner css has a bug that causes the animation to be jittery instead of smooth as it spins
![image](https://user-images.githubusercontent.com/49160279/109354594-0fa12a00-784c-11eb-846f-edbd8006438b.png)

**To Reproduce**
1. Go to Vetting or Flights on dev
2. As the table data loads, observe that the spinner arc animation is jittery or janky as it spins

locally, you can set your connection speed from online to slow 3g (Network tab) to give the spinner more display time)
![image](https://user-images.githubusercontent.com/49160279/109357465-40835e00-7850-11eb-8bbb-56769d5b255c.png)

**Expected behavior**
It should be smooth

**Comment by sylbakar** [comment]
Tested in dev and found expected result. The test passed.
