### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#672]
**Describe the bug**
The edit mode translations are saving in the database and can be seen on the Language Editor page, but the actual translatable fields on the page are not being translated anymore. This is reproducible on dev only, not locally.

**To Reproduce**
1. As an admin (dev env), go to the language editor page
2. Click on Live Edit
3. Edit any editable text on the page and save
4. Observe that when the page reloads, it does not reflect the page
5. Page through the table results of edits for the edit you just made
6. Observe that the change is reflected there, meaning it did save to db.

**Expected behavior**
The page should be updated with all live edit changes for the applicable language.

**Notes**
In dev tools > networking tab, the fetch for the page translations appears to be returning javascript rather than the expected json. The request header also does not have the "router" tag appended, though it is using the same base header configs as most other calls to the backend.

**Comment by sylbakar** [comment]
Tested in dev and found Translation worked. the test passed.
