### ISSUE TITLE
Password validation - show which requirements are passed or failed

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#677]
**Is your feature request related to a problem? Please describe.**
We need a clear client-side indication of which password requirements have been met. When the user is attempting to update a password, the system does not indicate violations.

**Describe the solution you'd like**
Where the password requirements are listed, the system should indicate which requirements have been passed or failed as the user types in a new password.

**Comment by sylbakar** [comment]
Tested in dev and found expected behavior.
