### ISSUE TITLE
Inline input validation

### ISSUE THREAD

**Issue by kasimhelil** [US-CBP/GTAS-UI#685]
**Is your feature request related to a problem? Please describe.**
Inputs fields such as password needs validations while the user type their inputs

To test:
1. As admin, go to the Change Password modal for your account or another user
2. As you type in the new password, verify that the icons correctly indicate whether you have met the criteria for each requirement

![inputvalidation](https://user-images.githubusercontent.com/49160279/111834651-49ed6c80-88ca-11eb-854b-90091bbc4e61.JPG)

**Comment by sylbakar** [comment]
Tested in dev and found input validation worked.
