### ISSUE TITLE
Flights | label is displayed as "FLights!!" instead of "Flights"

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#687]
**Describe the bug**
Flights' Tab label is displayed as "FLights!!" instead of "Flights"
**To Reproduce**
1. Go to Flights page
4. Notice Flights' Tab label is displayed as "FLights!!"

**Expected behavior**
Flights' Tab label is displayed as "Flights"

**Screenshots**
![image](https://user-images.githubusercontent.com/49790901/110504992-b8148100-80cb-11eb-9985-cf346854d24a.png)

**Desktop (please complete the following information):**
Tested in dev.

**Comment by gtasautumn** [comment]
This one is not a bug. The English (en) text has been translated with test text:

![image](https://user-images.githubusercontent.com/49160279/110509329-fc098500-80cf-11eb-9a77-2bc5a78120ae.png)

I did notice, however, that when I changed it back some of the translations in the header failed and the page went blank when I navigated around, which would indicate there is still a bug lurking there. I'll enter a new ticket to flush it out.
