### ISSUE TITLE
Add to Watchlist | Edit Translation | Default Text goes out of modal area

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#696]
**Describe the bug**
Default Text goes out of modal area

**To Reproduce**
1. Check Live edit
2. Go to any passenger detail page
3. Click on Add to Watchlist icon
4. Click on long text area on the modal
5. Notice Default Text goes out of modal area

**Expected behavior**
Default Text should be inside of modal area

**Screenshots**
![image](https://user-images.githubusercontent.com/49790901/111374857-00a3df80-8674-11eb-90d7-83ad531acd9d.png)

**Desktop (please complete the following information):**
Tested in dev

**Comment by gtasautumn** [comment]
good catch

**Comment by sylbakar** [comment]
tested in dev and found Default Text  inside of modal area. The test passed.
