### ISSUE TITLE
Multiselect default text translations

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#701]
**Is your feature request related to a problem? Please describe.**
Need to enable translations on the default text in multiselect dropdowns. See the User modal under Admin > Manage users. The role dropdown has default text that should be translatable

![multiselecttranslations](https://user-images.githubusercontent.com/49160279/111795160-53acab00-889d-11eb-914b-1833a67569ce.JPG)

**Comment by sylbakar** [comment]
Tested in dev and found both default text translatable. The test passed.
