### ISSUE TITLE
Audit/Error log - timestamp does not include seconds

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#703]
**Describe the bug**
v1.14 shows the seconds in the Timestamp column on the Audit log and Error log pages. 

![auditlogtimestampseconds](https://user-images.githubusercontent.com/49160279/111800953-d84df800-88a2-11eb-9d04-d5b0dfe71575.JPG)

**Comment by sylbakar** [comment]
Tested in dev and found seconds included in timestamp. the test passed.
