### ISSUE TITLE
Flightpax - DOB column filtering inaccurate

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#704]
**Describe the bug**
Found some bad results when filtering the DOB column in DEV. Problem is that the DOB field source data includes a sortable date (not displayed) that throws the results off when it matches the filter. The dates are also not zero-padded, but they should be.

**Screenshots**
![flightpaxdob1](https://user-images.githubusercontent.com/49160279/111820984-8617d180-88b8-11eb-8d9c-310668b0e54d.JPG)
![flightpaxdob2](https://user-images.githubusercontent.com/49160279/111821008-8ca64900-88b8-11eb-9c6c-22ea228e1c7b.JPG)

**Environment**
Dev

**Comment by sylbakar** [comment]
Tested in dev and found DOB filtering worked accurately. The test passed.
