### ISSUE TITLE
Flightpax - disable filter on Hit Aggregates column

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#706]
**Describe the bug**
We only need the sort on this column, plus the filter only works on the hidden sorting data for that column.

![hitaggregatesfilter](https://user-images.githubusercontent.com/49160279/111831402-b3b74780-88c5-11eb-9ecd-3f1cf9d686a5.JPG)

**Comment by sylbakar** [comment]
Tested in dev and found disable filter on Hit Aggregates column. The test passed.
