### ISSUE TITLE
Watchlist - pax DOB not sorting correctly

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#711]
**Describe the bug**
On Tools > Watchlist > Passenger tab, the DOB is sorted as a string in the format mm/dd/yyyy so that it does not sort chronologically.

We can use the sortableDob function as a hidden string prepended to the value as soon as that changed gets PRed into dev

**Comment by sylbakar** [comment]
Tested in dev and found sorting worked correctly however column filtering did not work:
I typed "09/" in the filter box and noticed blank:
![image](https://user-images.githubusercontent.com/49790901/114408733-b715ba00-9b77-11eb-9ebb-3fd2ff493d19.png)

**Comment by sylbakar** [comment]
Tested in dev and found expected result. The test passed.
