### ISSUE TITLE
Audit log - timestamp sort not working

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#715]
**Describe the bug**
The sort on the Timestamp column is not working. Running from 1pm Mar 31 to 1pm April 1 and sorting on the timestamp col, the dates appear to sort, but the April dates are sandwiched between the March dates when sorted either ascending or descending.

**Expected behavior**
The timestamp dates should sort chronologically

**Environment**
Dev

**Comment by sylbakar** [comment]
Tested in dev and found sorting worked correctly. The test passed.
