### ISSUE TITLE
Header's search form refreshes the entire page when pressing enter

### ISSUE THREAD

**Issue by kasimhelil** [US-CBP/GTAS-UI#717]
**Describe the bug**
After typing input text and hit `enter` on the header's search, the whole page refreshes

**To Reproduce**
1. Type anything on the search box and hit `enter` key and notice that it triggers  hard refresh on the page

**Expected behavior**
It should navigate to the search result page without hard refreshing the entire page.

**Comment by sylbakar** [comment]
Tested in dev and found expected behavior. The test passed.
