### ISSUE TITLE
Center seat chart data

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#724]
**Describe the bug**
Minor - arrange the data so it's centered. Issue is that many commercial flights max out at 30 rows or so, but even on larger planes, the width of the occupied rows can be much smaller than the viewport. The content should be centered.

![centerseatchart](https://user-images.githubusercontent.com/49160279/114784848-c8aebb80-9d49-11eb-9576-ee2be2e52294.JPG)

**To Test**
1. Find a flight with fewer than 100 or so passengers
2. Choose a passenger and view the seat chart
3. Verify that the seat grid aligns in the center of the content area
4. Repeat the above for a flight with 200 or more passengers or reduce the width of your browser so that the scrollbar under the seat chart is visible
5. Verify that the first and last rows of the flight are viewable and not cut off at the edges

**Comment by sylbakar** [comment]
Seat rows' numbering is not sequential.

**Comment by gtasautumn** [comment]
Do you mean the XXX rows? Can you share a screenshot? This may be a separate existing issue.

**Comment by sylbakar** [comment]
I mean missing numbers like here  missing 3, 4, 5 rows:
![image](https://user-images.githubusercont ent.com/49790901/115069513-a8a20800-9ec1-11eb-9172-3fc4d2f2615f.png)

**Comment by gtasautumn** [comment]
That's by design. The rows missing have no assigned seats, so they get skipped in the layout. If we change this going forward, it will be as a separate feature ticket.

**Comment by sylbakar** [comment]
Some row numbering are not ordered:
![image](https://user-images.githubusercontent.com/49790901/115250774-e4beae00-a0f7-11eb-9a0d-012152bf6dbd.png)

**Comment by gtasautumn** [comment]
good catch, thanks. Will take a look

**Comment by gtasautumn** [comment]
putting the ordering issue in a separate ticket since that is a different issue.
