### ISSUE TITLE
FlightPax - missing flight data sidebar 

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#727]
**Describe the bug**
When landing on the flightpax page from anywhere but the flights page, the flight data is missing in the sidebar. The issue is that the flights page passes the flight data to flightpax in state, but other pages do not. It's a bad pattern even if the other pages have this data, however, because if someone saves a link to a given flightpax page, the flight data will always be blank.

**Expected behavior**
The flightpax page should be responsible for fetching its own data. We can either eliminate passing flight data to it completely, or have it fetch only when that data is not populated.

**Screenshots**
![flightpaxmissingdataok](https://user-images.githubusercontent.com/49160279/114796097-0fa6ac00-9d5e-11eb-8685-f52b2d8a90a4.JPG)

![flightpaxmissingflightdatabad](https://user-images.githubusercontent.com/49160279/114796150-2fd66b00-9d5e-11eb-8a10-e484906bfd33.JPG)

**Comment by sylbakar** [comment]
Similar type issue was listed:
flightpax | missing values for Direction and Passengers #580

**Comment by sylbakar** [comment]
Tested in dev and found data in sidebar as expected. The test passed.
