### ISSUE TITLE
Any file larger than 1MB is not uploaded as Attachment

### ISSUE THREAD

**Issue by sylbakar** [US-CBP/GTAS-UI#728]
**Describe the bug**
Any file larger than 1 MB is not uploaded through Attachment modal

**To Reproduce**
1. Go to any passenger detail page
2. Click on Add Attachment icon
3. Try to upload any file larger than 1 MB  through Attachment modal
4. Notice the file is not uploaded and there is no error  message 

**Expected behavior**
 The file(up to 3 MB) should be  uploaded.

**Screenshots**

**Desktop (please complete the following information):**
tested in Dev

**Comment by tjwdev** [comment]
The nginx config for our dev environment has our payload limitation too low. Changing the config in the nginx file for client_max_body_size will fix this issue.

![image](https://user-images.githubusercontent.com/20208544/115687218-f6869800-a327-11eb-8f25-f513c57d42e4.png)

**Comment by tjwdev** [comment]
pull request #729 should fix this issue
