### ISSUE TITLE
Password Validation

### ISSUE THREAD

**Issue by kasimhelil** [US-CBP/GTAS-UI#762]
**Describe the bug**
Inline Password validation tooltip doesn't work

**To Reproduce**
1. Go to `Admin -> Manage User`
2. Click on 'Add User Icon at the bottom right corner of the page'
3. Enter invalid password; e.g "pass"
4. Hover over on the red info icon next to the input box

**Expected behavior**
You should see the password constraints

**Comment by gtasautumn** [comment]
good catch
