### ISSUE TITLE
carrier image is not square

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#783]
Tiny ticket, but the carrier image is 30x25 in the Flight grid possibly other locations, and stretches the images a bit.

**Comment by gtasautumn** [comment]
this is corrected in pr #765 :)

**Comment by gtasautumn** [comment]
oops!

**Comment by sylbakar** [comment]
Tested in dev and found Flights page carrier icon does not have zoom icon

**Comment by sylbakar** [comment]
Question: Do we need space between carrier icon and flight #?
![image](https://user-images.githubusercontent.com/49790901/120574737-e1545d00-c3ed-11eb-9866-5f79c51f38b9.png)

**Comment by gtasautumn** [comment]
> Tested in dev and found Flights page carrier icon does not have zoom icon

That's a separate ticket

**Comment by gtasautumn** [comment]
> Question: Do we need space between carrier icon and flight #?
> ![image](https://user-images.githubusercontent.com/49790901/120574737-e1545d00-c3ed-11eb-9866-5f79c51f38b9.png)

Yes, the space there is intentional
