### ISSUE TITLE
Misc table layout issues

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#790]
**Describe the bug**

4 bugs, 1 enhancement:

1. Flight and Vetting pages - The Countdown timer col centers text erratically. The CSS needs fixing so it displays the text and badge centered consistently inside the column
![image](https://user-images.githubusercontent.com/49160279/120230091-93d4c600-c21c-11eb-84e7-b32f7ad5b335.png)

2. Vetting page - on some screen widths, there is no separation between the flight date and time data
![image](https://user-images.githubusercontent.com/49160279/120230294-034ab580-c21d-11eb-8f6c-7edf83b04013.png)

3. Vetting - need a space between the carrier image and the flight number
![image](https://user-images.githubusercontent.com/49160279/120230414-38ef9e80-c21d-11eb-944d-b38992fac9ac.png)

4. Vetting - Biographic Info column data overruns the column boundary when the screen width is small enough to trigger the horizontal scrollbar
![image](https://user-images.githubusercontent.com/49160279/120230619-bb785e00-c21d-11eb-880f-4b72e3177c0f.png)
 
5. Rename the Carrier column to Flight (enhancement)

**Comment by sylbakar** [comment]
Tested in dev and found expected results. The test passed.
