### ISSUE TITLE
Wrong carrier name on Flightpax side nav

### ISSUE THREAD

**Issue by kasimhelil** [US-CBP/GTAS-UI#792]
**Describe the bug**
Flightpax side nave displays wrong carrier name if we navigate to the page from seat chart

**To Reproduce**
1. Go to 
 -  Flight pax page and after checking the carrier code name click on `All` to navigate to Seat charts.
 - From seat chart page click on `Show flight passengers` and notice that the carrier name is different from the first one.

**Expected behavior**
It should display the same carrier code

**Comment by sylbakar** [comment]
Tested in dev and found expected behavior. The test passed.
