### ISSUE TITLE
Vetting timer sort not working

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#793]
**Describe the bug**
The last update to remove unneeded fields removed the countdowntimer field from the resultset. Countdowntimer is a calculated field that can be derived on the front-end since its just the delta between the eta or etd datetime and now. Replaced it with the same calculation used elsewhere for the countdown badge.

Ultimately could refactor that code inside the countdown badge and just pass it the flight direction and both dates to simplify calling it.

**Comment by sylbakar** [comment]
Tested in dev and found timer sort working as expected.
