### ISSUE TITLE
Missing popovers

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#804]
**Is your feature request related to a problem? Please describe.**
On paxdetail, add a carrier detail popover to the flight number
![image](https://user-images.githubusercontent.com/49160279/120516103-fead0b00-c39c-11eb-8776-71935b1dfd3d.png)

On Vetting, pull the nationality icon out of the link and enable the zoom popover.
![image](https://user-images.githubusercontent.com/49160279/120516278-2b612280-c39d-11eb-979b-225845dc698a.png)

**Comment by sylbakar** [comment]
Tested in dev and found carrier detail popover to the flight number  and zoom popover to the flag icon. The test passed.
