### ISSUE TITLE
Forgot Username form issues

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#808]
**Describe the bug**

## issue 1
The forgot username form does not work when you open the site in a new browser window. If you enter a valid user email, it just refreshes the page when you hit submit. Looking in devtools, the issue seems to be that the fetch requires an existing session token, so we may need to correct the security for the handler.

![image](https://user-images.githubusercontent.com/49160279/121413450-b14c1300-c933-11eb-961b-d182912f0faa.png)

## issue 2
After you log in once and then log back out, Forgot Username is able to reach the api, but the form then triggers the same "email not found " message whether the email matches a user email or not.

![image](https://user-images.githubusercontent.com/49160279/121400017-0d5b6b00-c925-11eb-821a-6f9d6ec9f9dd.png)

**Comment by sylbakar** [comment]
Tested in dev and found issues were fixed. The test passed.
