### ISSUE TITLE
Center titles vertically

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#811]
**Is your feature request related to a problem? Please describe.**
minor css tweak to align the page titles to vertical center per Dave

all pages with tabs (flights, flightpax, paxdetail, admin code editor, admin filedownload, tools rules) and ensure that the header is vertically centered in its banner and has the same placement as all the other pages.

**Comment by sylbakar** [comment]
Tested in dev environment and found expected result.
