### ISSUE TITLE
minor - extra space in translation results

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#826]
**Describe the bug**
There's an extra space in the translation tag return that can be seen on the countdown badge. See below, there is a space between each timepart value and the timepart text (where the pink dots are)

![image](https://user-images.githubusercontent.com/49160279/122828241-632ffb80-d2b3-11eb-9e55-92f8c7c3bfaf.png)

They should look like this:
![image](https://user-images.githubusercontent.com/49160279/122828301-7c38ac80-d2b3-11eb-955d-6b38f2af0e3c.png)

**Comment by sylbakar** [comment]
Tested in dev and found expected result. The test passed.
