### ISSUE TITLE
Login input css conflict

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS-UI#833]
**Describe the bug**
Minor annoyance - the css on the login page applies slightly different rules the first time you load the site. Note the width of the input boxes.

First load, inputs are much wider than the header text:
![image](https://user-images.githubusercontent.com/49160279/123302598-de2f2700-d4ea-11eb-823b-add880aa652e.png)

then hit refresh and they are slimmer:
![image](https://user-images.githubusercontent.com/49160279/123302795-10408900-d4eb-11eb-99a2-fbfef166ced5.png)

The layout shouldn't change.

**Comment by sylbakar** [comment]
Tested in dev and found expected result. The test passed.
