### ISSUE TITLE
Create SQL script for table change on Feature/UI

### ISSUE THREAD

**Issue by tjwdev** [US-CBP/GTAS-UI#99]
On releases on our GTAS repo we add the SQL scripts to be run for 'upgrades' as part of our release, both an initial script and a rollback script. Though our changes to the back-end are hopefully not too egregious, table changes have happened now and this ticket is an attempt to track those so that upon merges eventually we can have those resultant SQL scripts accounted in some way.

To Be Added: SQL script for User table change to add "archived" element.

**Comment by gtasautumn** [comment]
this one is OBE by a previous fix that eliminates the need for a script. Null values in the archived field are no longer erroneously counted as archived, but are treated the same as false values.
